### ISSUE TITLE
3.0.0

### ISSUE THREAD

**Issue by frodsan** [hyperoslo/cellular#29]
- [ ] Remove unneeded dependencies (e.g. adding savon when only using the Twilio backend).
- [ ] Check what backends should we support.
- [ ] #26 Don't mutate given options hash.
- [ ] #28 Be able to configure default queue name.
- [ ] #2 Check if SMS was delivered

**Comment by frodsan** [comment]
@timkurvers what do you think?

**Comment by fespinoza** [comment]
the point with #2 is also to have "error handling"

**Comment by frodsan** [comment]
Example of Twilio adapter using net/http: https://gist.github.com/frodsan/5fefe36580b44de4689c67a8b889277a
